// js/utils/levels.js
// Level definitions for Ant War campaign mode.
// Each level progressively scales difficulty via concrete parameters.

const LEVELS = [
    {
        id: 1,
        name: "Scout Patrol",
        subtitle: "A small skirmish on the frontier",
        description: "The enemy is testing your defenses. Stay sharp, Commander.",
        // Player params
        playerMoundHealth: 100,
        playerStartFighters: 2,
        playerStartGatherers: 1,
        // AI params
        aiMoundHealth: 70,
        aiStartFighters: 2,
        aiStartGatherers: 1,
        aiStartMegas: 0,
        aiStartResources: 0,
        aiFighterAutoSpawn: true,
        // Timing (ms)
        fighterSpawnInterval: 10000,
        foodSpawnInterval: 5000,
        aiDecisionInterval: 3000,
        // Economy
        initialFoodCount: 5,
        maxFoodSources: 25,
        foodResourceValue: 5,
        // AI personality (multipliers on random buy chances)
        aiAggressiveness: 0.8,
        aiBombChance: 0.05,
        aiMegaChance: 0.2,
        aiGathererChance: 0.5,
        aiFighterChance: 0.6,
    },
    {
        id: 2,
        name: "Foraging Rights",
        subtitle: "The enemy sends more gatherers",
        description: "They are hoarding resources. Out-collect them before they overwhelm you.",
        playerMoundHealth: 100,
        playerStartFighters: 2,
        playerStartGatherers: 1,
        aiMoundHealth: 90,
        aiStartFighters: 3,
        aiStartGatherers: 2,
        aiStartMegas: 0,
        aiStartResources: 10,
        aiFighterAutoSpawn: true,
        fighterSpawnInterval: 9000,
        foodSpawnInterval: 4500,
        aiDecisionInterval: 2500,
        initialFoodCount: 6,
        maxFoodSources: 22,
        foodResourceValue: 5,
        aiAggressiveness: 1.0,
        aiBombChance: 0.05,
        aiMegaChance: 0.25,
        aiGathererChance: 0.6,
        aiFighterChance: 0.65,
    },
    {
        id: 3,
        name: "Territory War",
        subtitle: "The enemy strikes back",
        description: "They have dug in. Your fighters won't be enough — build your army.",
        playerMoundHealth: 100,
        playerStartFighters: 3,
        playerStartGatherers: 1,
        aiMoundHealth: 120,
        aiStartFighters: 4,
        aiStartGatherers: 2,
        aiStartMegas: 0,
        aiStartResources: 15,
        aiFighterAutoSpawn: true,
        fighterSpawnInterval: 8000,
        foodSpawnInterval: 4500,
        aiDecisionInterval: 2500,
        initialFoodCount: 6,
        maxFoodSources: 20,
        foodResourceValue: 5,
        aiAggressiveness: 1.1,
        aiBombChance: 0.1,
        aiMegaChance: 0.3,
        aiGathererChance: 0.5,
        aiFighterChance: 0.7,
    },
    {
        id: 4,
        name: "Colony Defense",
        subtitle: "Mega warriors emerge",
        description: "The enemy has bred Mega Fighters. You need heavy hitters of your own.",
        playerMoundHealth: 100,
        playerStartFighters: 2,
        playerStartGatherers: 2,
        aiMoundHealth: 130,
        aiStartFighters: 3,
        aiStartGatherers: 2,
        aiStartMegas: 1,
        aiStartResources: 20,
        aiFighterAutoSpawn: true,
        fighterSpawnInterval: 7000,
        foodSpawnInterval: 4000,
        aiDecisionInterval: 2000,
        initialFoodCount: 7,
        maxFoodSources: 20,
        foodResourceValue: 5,
        aiAggressiveness: 1.2,
        aiBombChance: 0.12,
        aiMegaChance: 0.35,
        aiGathererChance: 0.45,
        aiFighterChance: 0.7,
    },
    {
        id: 5,
        name: "Desert Storm",
        subtitle: "Sand bombs rain down",
        description: "The enemy commands the sands themselves. Prepare for bombardment.",
        playerMoundHealth: 100,
        playerStartFighters: 3,
        playerStartGatherers: 1,
        aiMoundHealth: 150,
        aiStartFighters: 4,
        aiStartGatherers: 2,
        aiStartMegas: 1,
        aiStartResources: 30,
        aiFighterAutoSpawn: true,
        fighterSpawnInterval: 6000,
        foodSpawnInterval: 4000,
        aiDecisionInterval: 2000,
        initialFoodCount: 6,
        maxFoodSources: 18,
        foodResourceValue: 4,
        aiAggressiveness: 1.3,
        aiBombChance: 0.2,
        aiMegaChance: 0.35,
        aiGathererChance: 0.4,
        aiFighterChance: 0.75,
    },
    {
        id: 6,
        name: "Siege of the Hive",
        subtitle: "The enemy surrounds you",
        description: "They have superior numbers and relentless attacks. Hold the line.",
        playerMoundHealth: 120,
        playerStartFighters: 3,
        playerStartGatherers: 2,
        aiMoundHealth: 180,
        aiStartFighters: 5,
        aiStartGatherers: 3,
        aiStartMegas: 2,
        aiStartResources: 40,
        aiFighterAutoSpawn: true,
        fighterSpawnInterval: 5000,
        foodSpawnInterval: 3500,
        aiDecisionInterval: 1500,
        initialFoodCount: 7,
        maxFoodSources: 16,
        foodResourceValue: 4,
        aiAggressiveness: 1.5,
        aiBombChance: 0.25,
        aiMegaChance: 0.4,
        aiGathererChance: 0.35,
        aiFighterChance: 0.8,
    },
    {
        id: 7,
        name: "Queen's Gambit",
        subtitle: "The queen unleashes her finest",
        description: "Only the most cunning strategies will survive. Every move counts.",
        playerMoundHealth: 130,
        playerStartFighters: 3,
        playerStartGatherers: 2,
        aiMoundHealth: 200,
        aiStartFighters: 5,
        aiStartGatherers: 3,
        aiStartMegas: 3,
        aiStartResources: 50,
        aiFighterAutoSpawn: true,
        fighterSpawnInterval: 4500,
        foodSpawnInterval: 3500,
        aiDecisionInterval: 1500,
        initialFoodCount: 6,
        maxFoodSources: 14,
        foodResourceValue: 3,
        aiAggressiveness: 1.6,
        aiBombChance: 0.3,
        aiMegaChance: 0.45,
        aiGathererChance: 0.3,
        aiFighterChance: 0.85,
    },
    {
        id: 8,
        name: "Apocalypse",
        subtitle: "Total annihilation",
        description: "The final battle. Give them everything you've got, Commander.",
        playerMoundHealth: 150,
        playerStartFighters: 4,
        playerStartGatherers: 2,
        aiMoundHealth: 250,
        aiStartFighters: 6,
        aiStartGatherers: 4,
        aiStartMegas: 4,
        aiStartResources: 60,
        aiFighterAutoSpawn: true,
        fighterSpawnInterval: 4000,
        foodSpawnInterval: 3000,
        aiDecisionInterval: 1200,
        initialFoodCount: 8,
        maxFoodSources: 15,
        foodResourceValue: 3,
        aiAggressiveness: 1.8,
        aiBombChance: 0.35,
        aiMegaChance: 0.5,
        aiGathererChance: 0.3,
        aiFighterChance: 0.9,
    }
];
